server:
  port: 8083

spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:mysql://localhost:3306/quickbite_restaurants?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.quickbite: DEBUG
    org.springframework.kafka: INFO
